# Starship prompt configuration

format = """
$os\
$username\
$hostname\ 
$directory\
$git_branch\ 
$git_status\
···\
$cmd_duration\
$time\
$line_break\
$python\
$character
"""

#right_format = """
#$cmd_duration\
#$time
#"""


# Use a two-line prompt like Powerlevel10k
add_newline = true


#palette = "candy"
#palette = "catppuccin_mocha"

[palettes.candy]
black = "#222222"
blue = "#00AAFF"
pink = "#FF79C6"
green = "#00FFB2"
purple = "#BD93F9"
red = "#FF5555"
white = "#F8F8F2"
yellow = "#F1FA8C"
cyan = "#54FFFF"
orange = "#FFA800"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Character that shows up at the start of the prompt ❯
[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

# Show OS icon using NerdFont
[os]
disabled = false
style = "bold cyan"
format = "[$symbol]($style) "

[os.symbols]
Windows = "󰍲"
Ubuntu = ""
Fedora = "󰣛"
Arch = "󰣇"
Debian = "󰣚"
Macos = "󰀵"
Linux = "󰌽"
Kali = ""

# Show username and hostname in format user@host
[username]
disabled = false
show_always = true
style_user = "bold white"
style_root = "bold white"
format = "[$user]($style)"

[hostname]
ssh_only = false
disabled = false
style = "bold white"
format = "[[@](bold red)$hostname]($style) "

# Show the current directory with folder icon
[directory]
truncation_length = 5
truncation_symbol = "…/"
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
style = "blue"
format = "· [󰝰 $path]($style) "

# Show git branch and status
[git_branch]
disabled = false
symbol = "  "
style = "yellow"
format = "· [$symbol$branch ]($style)"

# Shows current git status
[git_status]
style = 'yellow'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '  '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '
format = '[($all_status$ahead_behind)]($style)'

# Show Python virtualenv if active
[python]
symbol = " "
version_format = "v$major.$minor"
disabled = false
style = "green"
format = "[$symbol($virtualenv )]($style)"

[conda]
style = "cyan"
format = "[($environment )]($style)"

# Show time on the right
[time]
disabled = false
format = "[ [](pink) $time]($style)"
time_format = "%R"
style = "white"

[fill]
symbol = "·"
style = "white"

# Separator line
[line_break]
disabled = false

[cmd_duration]
min_time = 500
style = "yellow"
format = ' [$duration]($style)'